require("config")
require("keybinds")
require("window-rules")
pcall(require, "custom")

-- 事件: https://wiki.hypr.land/Configuring/Advanced-and-Cool/Expanding-functionality/#events

hl.on("hyprland.start", function () 
    hl.exec_cmd("fcitx5 -d --replace")
    hl.exec_cmd("awww-daemon")
    hl.exec_cmd("systemctl --user start waybar.service")
    hl.exec_cmd("systemctl --user start hyprpolkitagent")
end)
hl.on("config.reloaded", function () 
    hl.exec_cmd("systemctl --user restart waybar")
    hl.exec_cmd("fcitx5 -d --replace")
end)

hl.on("monitor.added", function ()
    hl.exec_cmd("fcitx5 -d --replace")
end)
-- hl.on("monitor.removed", function ()
--     hl.notification.create({ text = "haha: removed", duration = 1000 })
-- end)
-- hl.on("monitor.focused", function ()
--     hl.notification.create({ text = "haha: focused", duration = 1000 })
-- end)
-- hl.on("monitor.layout_changed", function ()
--     hl.notification.create({ text = "haha: layout_changed", duration = 1000 })
-- end)