# 选中 字背景色: 系统(#009779) 春日绿(#407434) 夏日红(#D63447) 秋日橙(#CD661D) 冬日蓝(#1D66CD)
[InputPanel/Highlight]
Color=#009779
[Menu/Highlight]
Color=#009779
[InputPanel]
# 选中 字颜色: 萤光绿(#54CE74) 透明萤光绿(#80FF00)， 需设置字背景色为#00030303
HighlightCandidateColor=#ffffff

# 面板
[InputPanel/Background]
Color=#000000dd
# Image=panel.png
# Image=panel-transparent.png

[Menu/Background]
Color=#ffffff
[Menu/Separator]
Color=#c0c0c0

[InputPanel]
# 非选中候选字颜色
NormalColor=#ffffff
# 高亮前景颜色(输入字符颜色)
HighlightColor=#ffffff
# 输入字符背景颜色
HighlightBackgroundColor=#00000000
# 字体
Font=Sans 13
# 
Spacing=3

[Metadata]
Name=base1
Version=0.1
Author=ly
Description=Fctix5 Base1 Theme
ScaleWithDPI=True

# 候选字边距
[InputPanel/TextMargin]
Left=10
Right=10
Top=3
Bottom=3

# 高亮区域边距
[InputPanel/Highlight/Margin]
Left=10
Right=10
Top=3
Bottom=3

[InputPanel/Background/Margin]
Left=2
Right=2
Top=2
Bottom=2

[Menu/Background/Margin]
Left=2
Right=2
Top=2
Bottom=2

[Menu/ContentMargin]
Left=2
Right=2
Top=2
Bottom=2

[Menu/Highlight/Margin]
Left=10
Right=10
Top=5
Bottom=5

[Menu/CheckBox]
Image=radio.png

[Menu/SubMenu]
Image=arrow.png

[Menu/TextMargin]
Left=5
Right=5
Top=5
Bottom=5
