font=Source Code Pro:size=10

[mouse]
hide-when-typing=yes

[colors-dark]
alpha=0.7
# blur=yes
background=000000
foreground=d1ba74

# folder
# regular4=d2e327
regular4=008457

# zsh-autosuggestions
bright0=8C979F
